version: '1'

services:
  web:
    containerDefinitions:
      web:
        cpu: 512
        memory: 512 # in MB
        essential: true
        command: "env PORT=3000 bundle exec foreman start web"
        portMappings:
          - containerPort: 3000
